WebApplication1/Controllers/HomeworkController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeworkController : Controller
    {
        public IActionResult homework1()
        {
            return View();
        }
        public IActionResult homework2()
        {
            return View();
        }  
        public IActionResult homework3()
        {
            return View();
        }  
        
        public IActionResult homework4()
        {
            return View();
        }

       
    }


}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                     
                        <li class="nav-item border border-success">
                            <a class="nav-link text-dark" style="font-weight:900" asp-area="" asp-controller="Homework" asp-action="homework1">homework1</a>
                        </li> 
                        <li class="nav-item border border-success">
                            <a class="nav-link text-dark" style="font-weight:900" asp-area="" asp-controller="Homework" asp-action="homework2">homework2</a>
                        </li> 
                        <li class="nav-item border border-success">
                            <a class="nav-link text-dark" style="font-weight:900" asp-area="" asp-controller="Homework" asp-action="homework3">homework3</a>
                        </li> 
                        <li class="nav-item border border-success">
                            <a class="nav-link text-dark" style="font-weight:900" asp-area="" asp-controller="Homework" asp-action="homework4">homework4</a>
                        </li>                                                
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>